name: core
services:
  core:
    networks:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5151
      - ASPNETCORE_HTTPS_PORTS=7124
      - ASPNETCORE_URLS=http://+:5151;https://+:7124
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=prn231;User=sa;Password=Password123!;MultipleActiveResultSets=true;Encrypt=false
    ports:
      - 5151:5151
      - 7124:7124
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      mssql:
        condition: service_healthy
    restart: on-failure
  mssql:
    environment:
      - SA_PASSWORD=Password123!
      - ACCEPT_EULA=Y
    ports:
      - 1434:1433
    volumes:
      - mssql-data:/data/db
    networks:
      - api
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q
        "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  mssql-data:
networks:
  api:
    name:  api