name: core
services:
  core:
    profiles: ["backend"]
    container_name: web-api
    image: web-api
    build:
      context: .
      dockerfile: Core/Dockerfile
    # depends_on:
    #   - mssql
  #   networks:
  #     - api
  mssql:
    profiles: ["backend"]
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest