@Core_HostAddress = http://localhost:5151
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwOGM1N2IzYi1hZWYzLTRmNDEtOGQ4ZS1kZDMzOWYyZGU4NTIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjFmYmYyMTdiLTRlOWEtNGQzMC1jYjM5LTA4ZGM3ZjczNjkzOCIsImVtYWlsIjoiOTI3Ny5kZXZAZ21haWwuY29tIiwic3ViIjoiOTI3Ny5kZXZAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InBoYW1xdWFuZ3ZpbmhmcHQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJQaOG6oW0gUXVhbmcgVmluaCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN1cGVyQWRtaW4iLCJleHAiOjE3MTcwNzA0MzcsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxMjQiLCJhdWQiOiJwaGFtcXVhbmd2aW5oIn0.0h85ZJTULBWJnfDlsmgZ9LikXZOYz19dWDbt85oYK80

GET {{Core_HostAddress}}/weatherforecast/
Accept: application/json

### Register
POST {{Core_HostAddress}}/api/Auth/Register
Content-Type: application/json

{
  "username": "string",
  "fullName": "string",
  "email": "user@example.com",
  "password": "string",
  "confirmPassword": "string",
  "phoneNumber": "string",
  "role": "string"
}

### Login
POST {{Core_HostAddress}}/api/Auth/Authenticate
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

### Logout
POST {{Core_HostAddress}}/api/Auth/Logout
Authorization : Bearer {{ accessToken }}

### Refresh Token
POST {{Core_HostAddress}}/api/Auth/RefreshToken
Content-Type: application/json

{
  "accessToken": "string",
  "refreshToken": "string"
}

### Confirm Email (Change string to actual values)
GET {{Core_HostAddress}}/api/Auth/ConfirmEmail?userId=string&token=string

### Forgot Password
POST {{Core_HostAddress}}/api/Auth/ForgetPassword?email=string

### Reset Password
POST {{Core_HostAddress}}/api/Auth/ResetPassword?Email=string&Token=string&NewPassword=string&ConfirmPassword=string

### Get List of Users
GET {{Core_HostAddress}}/api/User
Authorization : Bearer {{ accessToken }}